# Generated by Django 5.1.4 on 2024-12-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_field',
            new_name='date_of_birth',
        ),
    ]
