# Generated by Django 5.1.4 on 2024-12-16 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_date_of_field_patient_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=50, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='patient.patient')),
                ('related_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('timings', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='patient.patient')),
            ],
        ),
    ]
